### ISSUE TITLE
index out of range error

### ISSUE THREAD

**Issue by don-tpanic** [yftah89/structural-correspondence-learning-SCL#2]
Hi,

I wonder if the following code can sometimes be problematic: the value of i might exceed its limit before the while loop terminates

 while (c<pivot_num):
        name= bigram_vectorizer.get_feature_names()[MIsorted[i]]

        s_count = getCounts(X_2_train_source,bigram_vectorizer_source.get_feature_names().index(name)) if name in bigram_vectorizer_source.get_feature_names() else 0
        t_count = getCounts(X_2_train_target, bigram_vectorizer_target.get_feature_names().index(name)) if name in bigram_vectorizer_target.get_feature_names() else 0
        if(s_count>=pivot_min_st and t_count>=pivot_min_st):
            names.append(name)
            pivotsCounts.append(bigram_vectorizer_unlabeled.get_feature_names().index(name))
            c+=1
         #   if(c<100):
              #  print "feature is ",name," it MI is ",RMI[MIsorted[i]]," in source ",s_count," in target ",t_count
        i+=1

Thanks,

**Comment by yftah89** [comment]
Thanks a lot for noticing :)
If for some dataset you can not find the desired amount of pivot features, i.e. enough features that meet the frequency condition, the code is indeed problematic.  
I applied quick fix as follow:
MIsorted,RMI=GetTopNMI(5000,CountVectorizer,X_2_train,train_target) (line 118).
The getTopNMI got 5000 as it first param instead of 2000, which can give you larger amount of candidates for pivots to choose from.
The code I used for my articles indeed used larger number for the SCL if I remember correct, 5000 seems sufficient but please correct me if its not. 
So your are welcomed to re-download the code and see if it works for you :)

Please notice that:
1) For certain dataset this might not be sufficient even if you set the first parameter to the number of overall features if the desired amount of pivots is too large, this is one of the limitations of pivot based domain adaptation methods.
2) You can get a lousy pivot features, the features are sorted by their MI with the target, I you can not get the desired amount of pivot features out of X and change the param in line 118 to 2X that means that the MI for your candidates might be too low for pivot based methods to work.
3) You can set the bar lower, if the frequency threshold is too high in line 128, you can set it lower but like in 2, this can get you some unwanted pivots.

Thanks for drawing my attention to this, please do not hesitate to ask any questions :)

**Comment by don-tpanic** [comment]
I do have another question. As Blitzer suggested in the paper section 2.2, pivots should be chosen based on both high frequency and high MI score. But you see there's a trade-off here that the most frequent features might have very low MI with the labels and vice versa. So in your implementation, first you do MI and then select pivots based on the occurrence of these high MI features.

My question is, by looking at what's printed out from 
 `print "feature is ",name," it MI is ",RMI[MIsorted[i]]," in source ",s_count," in target ",t_count`. It seems that some features in both domains still have quite low overall occurrence (e.g. feature `better off` had source freq = 25 and target freq = 27) and some features seem to be occurring very often in one domain but not as often in the other domain (e.g. `get it` appears in source 1373, target 3081). So I wonder quite a few of these pivots might not be very good choice of pivots.

I haven't tried it yet but I wonder you might have done so --- would it make more sense to first select features based on their cross-domain frequency to make sure they appear equally often in both domains and then do MI. Not sure if this would make much of a difference though as I said it seems like a trade-off.


Thanks a lot for your time

**Comment by yftah89** [comment]
IMHO, minimal frequency is much more intuitive threshold compered to minimal MI.
I think that sorting by high MI and then dismiss the low frequency features is the right way to go.
I also think that this is what every pivot-based method is doing.

You are right that changing the threshold may change the results, but I would rather deal with the algorithmic side of things than the hyper-parameters of the learning pipeline, there are many more if you really think about it :)

**Comment by don-tpanic** [comment]
I get what you mean. But like I said you may end up with choosing many pivots which only appear in less than 1% of the reviews if you sort by MI first

Guess I just have to try it out :)

BTW, I just realise Blitzer only required pivots occur in more than 5 documents in each domain ... I find that quite counterintuitive to how I understand what a pivot feature is...

**Comment by yftah89** [comment]
You really have a lot of "small" decisions to take, in the original paper they write "we require that
pivots occur in more than five documents in each domain", in my preprocessing the threshold is doubled, so the problem you are describing is even worse in the original paper, but I really don't think that tuning those parameters is very interesting thing to do :)

**Comment by don-tpanic** [comment]
Not interesting at all!! Thanks a lot. Let's close this one for now 👍
